language: minimal
sudo: required
dist: trusty
env:
  matrix:
    - EMACS=emacs23
    - EMACS=emacs24
    - EMACS=emacs25
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot

branches:
  only:
    - master

install:
  - if [ "$EMACS" = 'emacs23' ]; then
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs23 emacs23-el;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs25' ]; then
        sudo add-apt-repository -y ppa:kelleyk/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs25 emacs25-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi

script:
  - $EMACS --version
  - $EMACS --batch -L . --eval "(and (>= emacs-major-version 24) (setq byte-compile-error-on-warn t))" -f batch-byte-compile julia-mode.el
  - if [ "$EMACS" != emacs23 ]; then
      $EMACS -batch -L . -l ert -l julia-mode-tests.el -f ert-run-tests-batch-and-exit;
    fi

notifications:
  email: false
