language: minimal
sudo: required
dist: xenial
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs25
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot

branches:
  only:
    - master

install:
  - if [ "$EMACS" = 'emacs25' ] || [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa;
    fi
  - sudo apt-get -qq update && sudo apt-get -qq -f install && sudo apt-get -qq install $EMACS $EMACS-el

script:
  - $EMACS --version
  - $EMACS --batch -L . --eval "(progn (and (>= emacs-major-version 24) (setq byte-compile-error-on-warn t)) (package-initialize) (package-install-file \"julia-mode.el\"))" -f batch-byte-compile julia-mode.el
  - $EMACS -batch -L . -l ert -l julia-mode-tests.el -f ert-run-tests-batch-and-exit;

notifications:
  email: false
